### ISSUE TITLE
~/Library/Preferences/WebStorm11/templates找不到

### ISSUE THREAD

**Issue by 542604974** [virtoolswebplayer/ReactNative-LiveTemplate#3]
你好，请问这个路径找不到，我放了ReactNative.xml到~/Library/Preferences/WebStorm11/没有效果，怎么办

**Comment by Zcgong** [comment]
@542604974 ~/Library/Preferences/WebStorm* /templates 这里的*表示你的web storm的文件夹 我的是WebStorm2016.2

**Comment by 542604974** [comment]
哦，谢谢，但我已经用Sublime Text了，轻量级也不错！

**Comment by virtoolswebplayer** [comment]
请详细看readme
